services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.4
    container_name: open-webui
    restart: always
    ports:
      - "8098:8080"
    environment:
      - USER_AGENT=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
    volumes:
      - open-webui:/app/backend/data

  open-terminal:
    image: ghcr.io/open-webui/open-terminal:0.14.0
    container_name: open-terminal
    restart: always
    volumes:
      - open-terminal:/home/user
    environment:
      OPEN_TERMINAL_API_KEY: ${OPEN_TERMINAL_API_KEY}

volumes:
  open-webui:
    external: true
  open-terminal:
    external: true
